# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-10-28 11:07-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: app/access_control/access_policy.py:147
msgid "Namespace in filename not found."
msgstr "未找到文件名中的命名空间。"

#: app/access_control/access_policy.py:166
msgid "Namespace not found."
msgstr "未找到命名空间。"

#: app/access_control/fields.py:17
msgid "object_roles field is required"
msgstr "object_roles 字段是必需的"

#: app/access_control/fields.py:21
msgid "id or name field is required"
msgstr "id 或 name 字段是必需的"

#: app/access_control/fields.py:27
msgid "object_roles must be a list of strings"
msgstr "object_roles 必须是一个字符串列表"

#: app/access_control/fields.py:35
msgid "Role {} does not exist"
msgstr "角色 {} 不存在"

#: app/access_control/fields.py:50
msgid "Groups must be a list of group objects"
msgstr "组必须是一个组对象的列表"

#: app/access_control/fields.py:68
#, python-format
msgid "Group name=%s, id=%s does not exist"
msgstr "组名=%s, id=%s 不存在"

#: app/access_control/fields.py:72 app/api/ui/serializers/user.py:156
msgid "Invalid group name or ID"
msgstr "无效的组名称或 ID"

#: app/access_control/mixins.py:55
#, python-brace-format
msgid ""
"Role {role} does not exist or does not have any permissions related to this "
"object."
msgstr "角色 {role} 不存在或没有与此对象相关的任何权限。"

#: app/api/ui/serializers/execution_environment.py:379
msgid "Selected registry does not exist."
msgstr "所选注册表不存在。"

#: app/api/ui/serializers/execution_environment.py:388
msgid ""
"Container names can only contain alphanumeric numbers, \".\", \"_\", \"-\" "
"and a up to one \"/\"."
msgstr "容器名称只能包含字母数字，\".\"、\"_\"、\"-\"，以及最多一个 \"/\"。"

#: app/api/ui/serializers/execution_environment.py:406
msgid "Name cannot be changed."
msgstr "名称不能更改。"

#: app/api/ui/serializers/synclist.py:38
#, python-brace-format
msgid "Repository \"{pulp_id}\" not found while creating synclist"
msgstr "创建同步列表时未找到存储库 \"{pulp_id}\""

#: app/api/ui/serializers/synclist.py:65
#, python-format
msgid "Synclist already exists: %s"
msgstr "同步列表已存在：%s"

#: app/api/ui/serializers/synclist.py:73
#, python-brace-format
msgid ""
"Collection \"{namespace}.{name}\" not found while creating synclist "
"{synclist}"
msgstr "创建同步列表 {synclist} 时未找到集合 \"{namespace}.{name}\""

#: app/api/ui/serializers/synclist.py:112
#, python-brace-format
msgid ""
"Collection \"{namespace}.{name}\" not found while updating synclist "
"{synclist}"
msgstr "更新同步列表 {synclist} 时未找到集合 \"{namespace}.{name}\""

#: app/api/ui/serializers/user.py:74
msgid ""
"'galaxy.change_group' permission is required to change a users group that "
"the requesting user is not in."
msgstr "更改请求用户不在的用户组需要具有 'galaxy.change_group' 权限。"

#: app/api/ui/serializers/user.py:89 app/api/ui/serializers/user.py:95
msgid "Must be a super user to grant super user permissions."
msgstr "必须是超级用户才能授予超级用户权限。"

#: app/api/ui/serializers/user.py:109
msgid "Must be a super user to change another user's password."
msgstr "必须是超级用户才能更改其他用户的密码。"

#: app/api/ui/serializers/user.py:125
msgid "You do not have permissions to modify super users."
msgstr "您没有修改超级用户的权限。"

#: app/api/ui/serializers/user.py:152
#, python-format
msgid "Group name=%(name)s, id=%(id)s does not exist"
msgstr "组名=%(name)s, id=%(id)s 不存在"

#: app/api/ui/views/feature_flags.py:50
msgid ""
"WARNING:GALAXY_COLLECTION_SIGNING_SERVICE is set to '{}', however the "
"respective SigningService does not exist in the database."
msgstr "WARNING:GALAXY_COLLECTION_SIGNING_SERVICE 设置为 '{}'，但对应的 SigningService 不数据库中不存在。"

#: app/api/ui/views/feature_flags.py:65
msgid ""
"WARNING:GALAXY_AUTO_SIGN_COLLECTIONS is set to True, however the system is "
"not configured with a SigningService to create signatures."
msgstr "WARNING:GALAXY_AUTO_SIGN_COLLECTIONS 设置为 True，但系统没有配置为使用 SigningService 来创建签名。"

#: app/api/ui/views/feature_flags.py:76
msgid ""
"INFO:System is configured to display signatures (coming from remote syncs) "
"but is not configured to create or accept upload of signatures."
msgstr "INFO:System 配置为显示签名（来自远程同步），但没有配置为创建或接受签名上传。"

#: app/api/ui/views/feature_flags.py:93
msgid ""
"WARNING:GALAXY_CONTAINER_SIGNING_SERVICE is set to '{}', however the "
"respective SigningService does not exist in the database."
msgstr "WARNING:GALAXY_CONTAINER_SIGNING_SERVICE 设置为 '{}'，但对应的 SigningService 不数据库中不存在。"

#: app/api/ui/views/feature_flags.py:106
msgid ""
"WARNING: container_signing is enabled via '{}' SigningService, however "
"execution environments are disabled on the system."
msgstr "WARNING: container_signing 通过 '{}' SigningService 启用，但执行环境在系统中被禁用。"

#: app/api/ui/views/index_execution_environments.py:36
msgid "Indexing execution environments is not supported on this registry."
msgstr "此注册表不支持索引执行环境。"

#: app/api/ui/views/signing.py:71
msgid "Missing required field: namespace"
msgstr "缺少所需字段：namespace"

#: app/api/ui/views/signing.py:88
#, python-format
msgid "No content units found for: %s"
msgstr "没有找到内容单元： %s"

#: app/api/ui/views/signing.py:103
msgid "distro_base_path field is required."
msgstr "distro_base_path 字段是必需的。"

#: app/api/ui/views/signing.py:108
#, python-format
msgid "Distribution %s does not exist."
msgstr "发布 %s 不存在。"

#: app/api/ui/views/signing.py:114
msgid "signing_service field is required."
msgstr "signing_service 字段是必需的。"

#: app/api/ui/views/signing.py:117
#, python-format
msgid "Signing service \"%s\" does not exist."
msgstr "签名服务 \"%s\" 不存在。"

#: app/api/ui/views/sync.py:37 app/api/v3/views/sync.py:34
#, python-format
msgid "The %s distribution does not have any remotes associated with it."
msgstr "%s 发行版没有任何与之关联的远程设备。"

#: app/api/ui/views/sync.py:51
#, python-format
msgid "The %s remote does not have any registries associated with it."
msgstr "%s 远程没有任何注册表与之关联。"

#: app/api/ui/viewsets/collection.py:77
msgid "Distribution base path is required"
msgstr "发布基础路径是必需的"

#: app/api/ui/viewsets/collection.py:221
msgid "Retrieve collection version"
msgstr "检索集合版本"

#: app/api/ui/viewsets/collection.py:232
msgid "Collection version not found for: {}"
msgstr "未找到集合版本：{}"

#: app/api/ui/viewsets/collection.py:288
msgid "Retrieve collection import"
msgstr "检索集合导入"

#: app/api/ui/viewsets/group.py:45
#, python-format
msgid "A group named %s already exists."
msgstr "名为 %s 的组已存在。"

#: app/api/utils.py:49
#, python-brace-format
msgid ""
"Invalid filename {filename}. Expected format: namespace-name-version.tar.gz"
msgstr "无效的文件名 {filename}。预期的格式：namespace-name-version.tar.gz"

#: app/api/utils.py:56
#, python-brace-format
msgid ""
"Invalid version string {version} from filename {filename}. Expected semantic "
"version format."
msgstr "来自文件名 {filename} 中的无效版本字符串 {version}。预期语义版本格式。"

#: app/api/utils.py:60
#, python-format
msgid "Expected namespace to be max length of %s"
msgstr "预期命名空间最大长度为 %s"

#: app/api/utils.py:62
#, python-format
msgid "Expected name to be max length of %s"
msgstr "预期名称最大长度为 %s"

#: app/api/utils.py:64
#, python-format
msgid "Expected version to be max length of %s"
msgstr "预期版本的最大长度为 %s"

#: app/api/v3/serializers/namespace.py:67
#, python-format
msgid "'%s' is not a valid url."
msgstr "'%s' 不是一个有效字符串。"

#: app/api/v3/serializers/namespace.py:100
msgid "Attribute 'name' is required"
msgstr "需要 'name' 属性"

#: app/api/v3/serializers/namespace.py:103
msgid "Name can only contain lower case letters, underscores and numbers"
msgstr "名称只能包含小写字母、下划线和数字"

#: app/api/v3/serializers/namespace.py:106
msgid "Name must be longer than 2 characters"
msgstr "名称必须大于 2 个字符"

#: app/api/v3/serializers/namespace.py:109
msgid "Name cannot begin with '_'"
msgstr "名称不能以 '_' 开头"

#: app/api/v3/serializers/sync.py:67
msgid "Password for proxy authentication."
msgstr "用于代理身份验证的密码。"

#: app/api/v3/serializers/sync.py:74
msgid "User for proxy authentication."
msgstr "用于代理身份验证的用户。"

#: app/api/v3/serializers/sync.py:87
msgid "Remote password."
msgstr "远程密码。"

#: app/api/v3/serializers/sync.py:94
msgid "Remote user."
msgstr "远程用户。"

#: app/api/v3/serializers/sync.py:148
msgid ""
"Syncing content from community domains without specifying a requirements "
"file is not allowed."
msgstr "不允许从社区域同步内容而不指定要求文件。"

#: app/api/v3/views/sync.py:45
msgid ""
"Syncing content from galaxy.ansible.com without specifying a requirements "
"file is not allowed."
msgstr "在不指定要求文件的情况下，不允许从 galaxy.ansible.com 同步内容。"

#: app/api/v3/viewsets/collection.py:109
#, python-format
msgid "Path does not match: \"%s\""
msgstr "路径不匹配：\"%s\""

#: app/api/v3/viewsets/collection.py:130
#, python-brace-format
msgid "Namespace \"{0}\" does not exist."
msgstr "命名空间 \"{0}\" 不存在。"

#: app/api/v3/viewsets/collection.py:224
#, python-format
msgid "Unexpected response from content app. Code: %s."
msgstr "来自内容应用的意外响应。代码：%s。"

#: app/api/v3/viewsets/collection.py:254
#, python-format
msgid "Collection %s not found"
msgstr "未找到集合 %s"

#: app/api/v3/viewsets/collection.py:262
#, python-format
msgid "Repo(s) for moving collection %s not found"
msgstr "未找到用于移动集合 %s 的存储库"

#: app/api/v3/viewsets/collection.py:267
#, python-format
msgid "Collection %s not found in source repo"
msgstr "源仓库中没有找到集合 %s"

#: app/api/v3/viewsets/collection.py:270
#, python-format
msgid "Collection %s already found in destination repo"
msgstr "目标仓库中已找到集合 %s"

#: app/api/v3/viewsets/collection.py:296 app/tasks/publishing.py:103
#, python-format
msgid "Signing %s service not found"
msgstr "未找到签名 %s 服务"

#: app/api/v3/viewsets/collection.py:306
#, python-brace-format
msgid ""
"Collection {namespace}.{name} could not be approved because system requires "
"at least a signature for approval."
msgstr "集合 {namespace}.{name} 无法批准，因为系统需要至少一个签名才能批准。"

#: app/api/v3/viewsets/namespace.py:67
#, python-format
msgid "A namespace named %s already exists."
msgstr "已存在名为 %s 的命名空间。"

#: app/api/v3/viewsets/namespace.py:88
#, python-brace-format
msgid ""
"Namespace {name} cannot be deleted because there are still collections "
"associated with it."
msgstr "命名空间 {name} 无法被删除，因为仍存在与其关联的集合。"

#: app/auth/keycloak.py:51
msgid "Authentication failed."
msgstr "认证失败。"

#: app/exceptions.py:8
msgid "Data conflicts with existing entity."
msgstr "数据与现有实体冲突。"

#: app/tasks/index_registry.py:26
#, python-brace-format
msgid "Failed to create container {remote_name}. {error}"
msgstr "创建容器失败 {remote_name}. {error}"

#: app/tasks/index_registry.py:90
msgid ""
"A remote container with this name already exists, but is not associated with "
"any registry."
msgstr "具有此名称的远程容器已存在，但不与任何注册表关联。"

#: app/tasks/index_registry.py:97
msgid "A local container with this name already exists."
msgstr "具有此名称的本地容器已经存在。"

#: app/tasks/publishing.py:57 app/tasks/publishing.py:94
#, python-format
msgid "Could not find staging repository: \"%s\""
msgstr "无法找到 staging 存储库：\"%s\""

