
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-02-17 04:14+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: nl\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: app/access_control/access_policy.py:87
msgid "Namespace in filename not found."
msgstr "Namespace in bestandsnaam niet gevonden."

#: app/access_control/fields.py:17
msgid "object_permissions field is required"
msgstr "Veld object_permissions is verplicht"

#: app/access_control/fields.py:21
msgid "id or name field is required"
msgstr "Veld id of naam is verplicht."

#: app/access_control/fields.py:27
msgid "object_permissions must be a list of strings"
msgstr "object_permissions moet een lijst van tekenreeksen zijn"

#: app/access_control/fields.py:41
msgid "Permission {} does not exist"
msgstr "Machtiging {} bestaat niet"

#: app/access_control/fields.py:56
msgid "Groups must be a list of group objects"
msgstr "Groepen moet een lijst van groepsobjecten zijn"

#: app/access_control/fields.py:71
#, python-format
msgid "Group name=%s, id=%s does not exist"
msgstr "Groepsnaam=%s, id=%s bestaat niet"

#: app/access_control/fields.py:75 app/api/ui/serializers/user.py:132
msgid "Invalid group name or ID"
msgstr "Ongeldige groepsnaam of id."

#: app/api/ui/serializers/execution_environment.py:375
msgid "Selected registry does not exist."
msgstr "Geselecteerd register bestaat niet."

#: app/api/ui/serializers/execution_environment.py:384
msgid ""
"Container names can only contain alphanumeric numbers, \".\", \"_\", \"-\" "
"and a up to one \"/\"."
msgstr "Containernamen kunnen alleen alfanumerieke getallen, \".\", \"_\", \"-\" en maximaal één \"/\" bevatten."

#: app/api/ui/serializers/execution_environment.py:402
msgid "Name cannot be changed."
msgstr "Naam kan niet worden veranderd."

#: app/api/ui/serializers/synclist.py:41
#, python-brace-format
msgid "Repository \"{pulp_id}\" not found while creating synclist"
msgstr "Repository \"{pulp_id}\" niet gevonden tijdens aanmaken synclist"

#: app/api/ui/serializers/synclist.py:96
#, python-format
msgid "Synclist already exists: %s"
msgstr "Synclist bestaat al: %s"

#: app/api/ui/serializers/synclist.py:104
#, python-brace-format
msgid ""
"Collection \"{namespace}.{name}\" not found while creating synclist "
"{synclist}"
msgstr "Collectie \"{namespace}.{name}\" niet gevonden tijdens het aanmaken van synclist {synclist}"

#: app/api/ui/serializers/synclist.py:143
#, python-brace-format
msgid ""
"Collection \"{namespace}.{name}\" not found while updating synclist "
"{synclist}"
msgstr "Collectie \"{namespace}.{name}\" niet gevonden tijdens het bijwerken van synclist {synclist}"

#: app/api/ui/serializers/user.py:74
msgid ""
"'galaxy.change_group' permission is required to change a users group that "
"the requesting user is not in."
msgstr "De machtiging 'galaxy.change_group' is nodig om een gebruikersgroep te veranderen waar de aanvragende gebruiker geen deel van uitmaakt."

#: app/api/ui/serializers/user.py:85
msgid "Must be a super user to grant super user permissions."
msgstr "Moet een supergebruiker zijn om machtigingen voor een supergebruiker te verlenen."

#: app/api/ui/serializers/user.py:128
#, python-format
msgid "Group name=%(name)s, id=%(id)s does not exist"
msgstr "Groepsnaam=%(name)s, id=%(id)s bestaat niet"

#: app/api/ui/views/index_execution_environments.py:36
msgid "Indexing execution environments is not supported on this registry."
msgstr "Het indexeren van uitvoeringsomgevingen wordt in dit register niet ondersteund."

#: app/api/ui/views/sync.py:37 app/api/v3/views/sync.py:34
#, python-format
msgid "The %s distribution does not have any remotes associated with it."
msgstr "De %s-distributie heeft geen items op afstand die ermee zijn geassocieerd."

#: app/api/ui/views/sync.py:51
#, python-format
msgid "The %s remote does not have any registries associated with it."
msgstr "De %s op afstand heeft geen registers die ermee zijn geassocieerd."

#: app/api/ui/viewsets/collection.py:60
msgid "Distribution base path is required"
msgstr "Basispad distributie is vereist"

#: app/api/ui/viewsets/collection.py:175
msgid "Retrieve collection version"
msgstr "Collectieversie ophalen"

#: app/api/ui/viewsets/collection.py:186
msgid "Collection version not found for: {}"
msgstr "Collectieversie niet gevonden voor: {}"

#: app/api/ui/viewsets/collection.py:242
msgid "Retrieve collection import"
msgstr "Collectie import ophalen"

#: app/api/ui/viewsets/group.py:45
#, python-format
msgid "A group named %s already exists."
msgstr "Een groep met de naam %s bestaat al."

#: app/api/utils.py:49
#, python-brace-format
msgid ""
"Invalid filename {filename}. Expected format: namespace-name-version.tar.gz"
msgstr "Ongeldige bestandsnaam {filename}. Verwachte indeling: namespace-naam-versie.tar.gz"

#: app/api/utils.py:56
#, python-brace-format
msgid ""
"Invalid version string {version} from filename {filename}. Expected semantic "
"version format."
msgstr "Ongeldige versie string {version} van bestandsnaam {filename}. Verwachte semantische versie indeling."

#: app/api/utils.py:60
#, python-format
msgid "Expected namespace to be max length of %s"
msgstr "Verwachte namespace met maximale lengte van %s"

#: app/api/utils.py:62
#, python-format
msgid "Expected name to be max length of %s"
msgstr "Verwachte naam met max. lengte van %s"

#: app/api/utils.py:64
#, python-format
msgid "Expected version to be max length of %s"
msgstr "Verwachte versie met max. lengte van %s"

#: app/api/v3/serializers/namespace.py:60
#, python-format
msgid "'%s' is not a valid url."
msgstr "\"%s\" is geen geldige url."

#: app/api/v3/serializers/namespace.py:88
msgid "Attribute 'name' is required"
msgstr "Een 'naam' voor het attribuut is vereist."

#: app/api/v3/serializers/namespace.py:91
msgid "Name can only contain lower case letters, underscores and numbers"
msgstr "De naam mag alleen kleine letters, underscores en cijfers bevatten"

#: app/api/v3/serializers/namespace.py:94
msgid "Name must be longer than 2 characters"
msgstr "Naam moet langer zijn dan 2 tekens"

#: app/api/v3/serializers/namespace.py:97
msgid "Name cannot begin with '_'"
msgstr "Naam kan niet met '_' beginnen"

#: app/api/v3/serializers/sync.py:66
msgid "Password for proxy authentication."
msgstr "Wachtwoord voor proxy-authenticatie."

#: app/api/v3/serializers/sync.py:73
msgid "User for proxy authentication."
msgstr "Gebruiker voor proxy-authenticatie."

#: app/api/v3/serializers/sync.py:86
msgid "Remote password."
msgstr "Wachtwoord op afstand."

#: app/api/v3/serializers/sync.py:93
msgid "Remote user."
msgstr "Gebruiker op afstand."

#: app/api/v3/serializers/sync.py:146
msgid ""
"Syncing content from community domains without specifying a requirements "
"file is not allowed."
msgstr "Het is niet toegestaan inhoud van gemeenschapsdomeinen te synchroniseren zonder een bestand met vereisten op te geven."

#: app/api/v3/views/sync.py:45
msgid ""
"Syncing content from galaxy.ansible.com without specifying a requirements "
"file is not allowed."
msgstr "Het is niet toegestaan inhoud van galaxy.ansible.com te synchroniseren zonder een bestand met vereisten op te geven."

#: app/api/v3/viewsets/collection.py:122
#, python-brace-format
msgid ""
"Collection {namespace}.{name} could not be deleted because there are other "
"collections that require it."
msgstr "Collectie {namespace}.{name} kon niet worden verwijderd omdat er andere collecties zijn die het nodig hebben."

#: app/api/v3/viewsets/collection.py:200
#, python-brace-format
msgid ""
"Collection version {namespace}.{name} {version} could not be deleted because "
"there are other collections that require it."
msgstr "Collectieversie {namespace}.{name} {version} kon niet worden verwijderd omdat er andere collecties zijn die het nodig hebben."

#: app/api/v3/viewsets/collection.py:292
#, python-format
msgid "Path does not match: \"%s\""
msgstr "Pad komt niet overeen: \"%s\""

#: app/api/v3/viewsets/collection.py:313
#, python-brace-format
msgid "Namespace \"{0}\" does not exist."
msgstr "Namespace \"{0}\" bestaat niet."

#: app/api/v3/viewsets/collection.py:401
#, python-format
msgid "Unexpected response from content app. Code: %s."
msgstr "Onverwachte reactie van inhoud app. Code: %s."

#: app/api/v3/viewsets/collection.py:431
#, python-format
msgid "Collection %s not found"
msgstr "Collectie %s niet gevonden"

#: app/api/v3/viewsets/collection.py:439
#, python-format
msgid "Repo(s) for moving collection %s not found"
msgstr "Repo('s) voor verplaatsen collectie %s niet gevonden"

#: app/api/v3/viewsets/collection.py:443
#, python-format
msgid "Collection %s not found in source repo"
msgstr "Collectie %s niet gevonden in bron-repo"

#: app/api/v3/viewsets/collection.py:447
#, python-format
msgid "Collection %s already found in destination repo"
msgstr "Collectie %s reeds gevonden in doel-repo"

#: app/api/v3/viewsets/namespace.py:67
#, python-format
msgid "A namespace named %s already exists."
msgstr "Een namespace met de naam %s bestaat al."

#: app/api/v3/viewsets/namespace.py:88
#, python-brace-format
msgid ""
"Namespace {name} cannot be deleted because there are still collections "
"associated with it."
msgstr "Namespace {name} kan niet worden verwijderd omdat er nog collecties aan zijn gekoppeld."

#: app/auth/keycloak.py:51
msgid "Authentication failed."
msgstr "Authenticatie mislukt."

#: app/exceptions.py:8
msgid "Data conflicts with existing entity."
msgstr "Gegevens conflicteren met bestaande entiteit."

#: app/tasks/index_registry.py:26
#, python-brace-format
msgid "Failed to create container {remote_name}. {error}"
msgstr "Kan container {remote_name}. {error} niet aanmaken"

#: app/tasks/index_registry.py:90
msgid ""
"A remote container with this name already exists, but is not associated with "
"any registry."
msgstr "Een container op afstand met deze naam bestaat al, maar is niet geassocieerd met een register."

#: app/tasks/index_registry.py:97
msgid "A local container with this name already exists."
msgstr "Een lokale container met deze naam bestaat al."

#: app/tasks/publishing.py:53 app/tasks/publishing.py:91
#, python-format
msgid "Could not find staging repository: \"%s\""
msgstr "Kon de staging repository niet vinden: \"%s\""

#: app/tasks/synclist.py:45
#, python-format
msgid "Curating all synclists repos that curate from %s"
msgstr "Cureren van alle synclists-repo's die cureren vanuit %s"

#: app/tasks/synclist.py:56
msgid "Synclists curating upstream repo"
msgstr "Synclisten cureren upstream repo"

#: app/tasks/synclist.py:63
msgid "Synclists curating upstream repo task"
msgstr "Synclisten cureren taak upstream repo"

#: app/tasks/synclist.py:91
#, python-format
msgid "Finishing curating %s synclist repos based on %s update"
msgstr "Afwerking van %s synclist-repo's gebaseerd op %s-update"

#: app/tasks/synclist.py:120
#, python-format
msgid ""
"Applying synclist \"%s\" with policy=%s to curate repo \"%s\" from upstream "
"repo \"%s\""
msgstr "Synclist \"%s\" toepassen met policy=%s om repo \"%s\" te cureren vanuit upstream repo \"%s\""

#: app/tasks/synclist.py:162
msgid "Unexpected synclist policy {}"
msgstr "Onverwachte policy synclist {}"
